
import React from 'react';

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();
  return (
    <footer className="w-full text-center py-8 px-4 mt-auto">
      <p className="text-xs text-gray-500 max-w-3xl mx-auto">
        Disclaimer: This analysis is generated by an AI based on public news data and should not be considered expert geopolitical advice. The situation is highly volatile and subject to change.
      </p>
      <p className="text-xs text-gray-600 mt-2">
        &copy; {currentYear} Geopolitical Analysis. All rights reserved.
      </p>
    </footer>
  );
};

export default Footer;